# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Coins' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Coins
  pod 'Swinject', '~> 2.0.0'
 	pod 'lottie-ios'

  target 'CoinsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoinsUITests' do
    # Pods for testing
  end

end
